language: python
python:
  - "3.8"
arch:
  - amd64
  - arm64
git:
  depth: false
services:
  - docker
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - pip install -r requirements-dev.txt
script: >-
  tools/push bitcoind:0.20.0 litecoind:0.18.1 geth:1.9.16
  lnd:0.10.2-beta lnd:0.10.2-beta-simnet
  lnd:0.10.1-beta-ltc lnd:0.10.1-beta-ltc-simnet
  connext connext:7.0.0-alpha.14
  xud xud:1.0.0-beta.5
  arby arby:0.2.0
  boltz boltz:1.0.0
  webui webui:1.0.0
notifications:
  webhooks:
    urls:
      - http://104.196.206.7:5000/webhooks/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always

cache:
  directories:
  - images/bitcoind/.src
  - images/litecoind/.src
  - images/geth/.src
  - images/lnd/.src
  - images/connext/.src
  - images/xud/.src
  - images/arby/.src
  - images/boltz/.src
  - images/webui/.src
