language: python
python:
  - "3.8"
arch:
  - amd64
  - arm64
git:
  depth: false
services:
  - docker
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - pip install -r requirements-dev.txt
script: tools/push
notifications:
  webhooks:
    urls:
      - http://104.196.206.7:5000/webhooks/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
