version: "3.6"

x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '5'
  driver: json-file

services:
  bitcoind:
    image: exchangeunion/bitcoind:0.18.1
    hostname: bitcoind
    environment:
      - NETWORK=mainnet
    command: >
      -server
      -rpcuser=xu
      -rpcpassword=xu
      -disablewallet
      -txindex
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333
      -logips
      -rpcport=8332
      -rpcallowip=::/0
      -rpcbind=0.0.0.0
    volumes:
      - ${BITCOIND_DIR:-./data/bitcoind}:/root/.bitcoin
    logging: *default-logging

  litecoind:
    image: exchangeunion/litecoind:0.17.1
    hostname: litecoind
    environment:
      - NETWORK=testnet
    command: >
      -server
      -rpcuser=xu
      -rpcpassword=xu
      -disablewallet
      -txindex
      -zmqpubrawblock=tcp://0.0.0.0:29332
      -zmqpubrawtx=tcp://0.0.0.0:29333
      -logips
      -rpcport=9332
      -rpcallowip=::/0
      -rpcbind=0.0.0.0
    volumes:
      - ${LITECOIND_DIR:-./data/litecoind}:/root/.litecoin
    logging: *default-logging

  lndbtc:
    image: exchangeunion/lnd:0.7.1-beta
    hostname: lndbtc
    environment:
      - NETWORK=mainnet
      - CHAIN=bitcoin
    env_file:
      - lnd.env
    ports:
      - 9735:9735
    volumes:
      - ./data/lndbtc:/root/.lnd
    logging: *default-logging

  lndltc:
    image: exchangeunion/lnd:0.7.1-beta
    hostname: lndltc
    environment:
      - NETWORK=mainnet
      - CHAIN=litecoin
    env_file:
      - lnd.env
    ports:
      - 10735:10735
    volumes:
      - ./data/lndltc:/root/.lnd
    logging: *default-logging

  geth:
    image: exchangeunion/geth:1.9.6
    hostname: geth
    environment:
      - NETWORK=mainnet
    volumes:
      - ${GETH_DIR:-./data/geth}:/root/.ethereum
      - ${GETH_CHAINDATA_DIR:-./data/geth/chaindata}:/root/.ethereum/chaindata
    logging: *default-logging

  raiden:
    image: exchangeunion/raiden
    hostname: raiden
    environment:
      - NETWORK=mainnet
    volumes:
      - ./data/raiden:/root/.raiden
    logging: *default-logging

  xud:
    image: exchangeunion/xud
    hostname: xud
    environment:
      - NETWORK=mainnet
    volumes:
      - ./data/xud:/root/.xud
      - ./data/lndbtc:/root/.lndbtc
      - ./data/lndltc:/root/.lndltc
      - ./data/raiden:/root/.raiden
    ports:
      - 8885:8885
    logging: *default-logging
