version: "3.6"

services:
  bitcoind:
    image: exchangeunion/bitcoind:0.18.1
    # Let generated "rpc.cert" has "btcd" domain name,
    # or it will deny lnd rpc connections
    hostname: bitcoind
    command: >
      -server
      -mainnet
      -rpcuser=xu
      -rpcpassword=xu
      -disablewallet
      -txindex
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333
      -logips
      -rpcport=8332
      -rpcallowip=::/0
      -rpcbind=0.0.0.0
    ports:
      - 8332:8332
      - 28332:28332
      - 28333:28333
    volumes:
      - ./data/bitcoind:/root/.bitcoin

  litecoind:
    image: exchangeunion/litecoind:0.17.1
    # Let generated "rpc.cert" has "ltcd" domain name,
    # or it will deny lnd rpc connections
    hostname: litecoind
    command: >
      -server
      -mainnet
      -rpcuser=xu
      -rpcpassword=xu
      -disablewallet
      -txindex
      -zmqpubrawblock=tcp://0.0.0.0:29332
      -zmqpubrawtx=tcp://0.0.0.0:29333
      -logips
      -rpcport=9332
      -rpcallowip=::/0
      -rpcbind=0.0.0.0
    ports:
      - 9332:9332
      - 29332:29332
      - 29333:29333
    volumes:
      - ./data/litecoind:/root/.litecoin

  lndbtc:
    image: exchangeunion/lnd:0.6.1-beta-rc2
    environment:
      - NETWORK=mainnet
      - CHAIN=bitcoin
    hostname: lndbtc
    command: >
      --alias=lndbtc
      --bitcoin.active
      --bitcoin.mainnet
      --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoind
      --bitcoind.rpcuser=xu
      --bitcoind.rpcpass=xu
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      --debuglevel=debug
    ports:
      - 10009:10009
    volumes:
      - ./data/lndbtc:/root/.lnd
    restart: on-failure:10

  lndltc:
    image: exchangeunion/lnd:0.6.1-beta-rc2
    environment:
      - NETWORK=mainnet
      - CHAIN=litecoin
    hostname: lndltc
    command: >
      --alias=lndltc
      --litecoin.active
      --litecoin.mainnet
      --litecoin.node=litecoind
      --litecoind.rpchost=litecoind
      --litecoind.rpcuser=xu
      --litecoind.rpcpass=xu
      --litecoind.zmqpubrawblock=tcp://litecoind:29332
      --litecoind.zmqpubrawtx=tcp://litecoind:29333
      --debuglevel=debug
    ports:
      - 20009:10009
    volumes:
      - ./data/lndltc:/root/.lnd
    restart: on-failure:10

  xud:
    image: exchangeunion/xudctl:1.0.0-alpha.11
    hostname: xud
    environment:
      - NETWORK=mainnet
    volumes:
      - ./data/xud:/root/.xud
      - ./data/lndbtc:/root/.lndbtc
      - ./data/lndltc:/root/.lndltc
    ports:
      - 8885:8885
      - 8886:8886
      - 8887:8887
  
  geth:
    image: exchangeunion/geth:1.9.1
    environment:
      - NETWORK=mainnet
    command: >
      --syncmode fast
      --rpc
      --rpcapi eth,net,web3,txpool,personal,admin
      --rpcaddr 0.0.0.0
      --rpcvhosts=*
    volumes: 
      - ./data/geth:/root/.ethereum
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303/udp

  raiden:
    image: exchangeunion/raiden:0.100.3
    environment:
      - NETWORK=mainnet
    command: >
      --keystore-path /root/.ethereum/testnet/keystore
      --resolver-endpoint http://xud:8887/resolveraiden
      --accept-disclaimer
      --eth-rpc-endpoint http://geth:8545
      --network-id 0
      --password-file /root/.raiden/password.txt
    ports:
      - 5001:5001
    volumes:
      - ./data/geth:/root/.ethereum
    restart: on-failure:10
