version: "3.6"

x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '5'
  driver: json-file

services:
  bitcoind:
    image: exchangeunion/bitcoind:0.18.1
    hostname: bitcoind
    environment:
      - NETWORK=mainnet
    command: >
      -server
      -rpcuser=xu
      -rpcpassword=xu
      -disablewallet
      -txindex
      -logips
      -rpcport=8332
    ports:
      - 8332:8332
      - 28332:28332
      - 28333:28333
    volumes:
      - ./data/bitcoind:/root/.bitcoin
    logging: *default-logging

  litecoind:
    image: exchangeunion/litecoind:0.17.1
    hostname: litecoind
    environment:
      - NETWORK=testnet
    command: >
      -server
      -rpcuser=xu
      -rpcpassword=xu
      -disablewallet
      -txindex
      -logips
      -rpcport=9332
    ports:
      - 9332:9332
      - 29332:29332
      - 29333:29333
    volumes:
      - ./data/litecoind:/root/.litecoin
    logging: *default-logging

  lndbtc:
    image: exchangeunion/lnd:0.7.1-beta
    hostname: lndbtc
    environment:
      - NETWORK=mainnet
      - CHAIN=bitcoin
    ports:
      - 9735:9735
      - 10009:10009
    volumes:
      - ./data/lndbtc:/root/.lnd
    logging: *default-logging

  lndltc:
    image: exchangeunion/lnd:0.7.1-beta
    hostname: lndltc
    environment:
      - NETWORK=mainnet
      - CHAIN=litecoin
    ports:
      - 10735:9735
      - 20009:10009
    volumes:
      - ./data/lndltc:/root/.lnd
    logging: *default-logging

  geth:
    image: exchangeunion/geth:1.9.1
    hostname: geth
    environment:
      - NETWORK=mainnet
    command: >
      --syncmode fast
      --rpc
      --rpcapi eth,net,web3,txpool,personal,admin
      --rpcvhosts=*
    volumes: 
      - ./data/geth:/root/.ethereum
    ports:
      - 30303:30303/udp
    logging: *default-logging
  
  raiden:
    image: exchangeunion/raiden
    hostname: raiden
    environment:
      - NETWORK=mainnet
    command: >
      --keystore-path /root/.ethereum/keystore
      --accept-disclaimer
      --resolver-endpoint http://xud:8887/resolveraiden
      --eth-rpc-endpoint geth:8545
      --network-id mainnet
      --password-file /root/.ethereum/passphrase.txt
      --datadir /root/.raiden
      --rpc
      --matrix-server https://raidentransport.exchangeunion.com
      --routing-mode private
      --environment-type production
      --tokennetwork-registry-contract-address 0xd32F5E0fF172d41a20b32B6DAb17948B257aa371
      --secret-registry-contract-address 0x322681a720690F174a4071DBEdB51D86E7B9FF84
      --service-registry-contract-address 0x281937D366C7bCE202481c45d613F67500b93E69
      --user-deposit-contract-address 0x4F26957E8fd331D53DD60feE77533FBE7564F5Fe
      --monitoring-service-contract-address 0x37cC37D7703554183aE544391945e7D0588b7693
      --one-to-n-contract-address 0x3dda5BE50Af796618d9f48c021Cf0C9FD64FFeb1
    ports:
      - 5001:5001
    volumes:
      - ./data/geth:/root/.ethereum
      - ./data/raiden:/root/.raiden
    logging: *default-logging

  xud:
    image: exchangeunion/xud
    hostname: xud
    environment:
      - NETWORK=mainnet
    volumes:
      - ./data/xud:/root/.xud
      - ./data/lndbtc:/root/.lndbtc
      - ./data/lndltc:/root/.lndltc
    ports:
      - 8885:8885
      - 8886:8886
      - 8887:8887
    logging: *default-logging

