version: "3.6"
x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '5'
  driver: json-file

services:
  ltcd:
    image: exchangeunion/ltcd-simnet
    # Let generated "rpc.cert" has "ltcd" domain name,
    # or it will deny lnd rpc connections
    hostname: ltcd
    environment:
      - NETWORK=simnet
    command: >
      --simnet
      --txindex
      --rpcuser=xu
      --rpcpass=xu
      --rpclisten=:18556
      --nolisten
      --addpeer=35.231.222.142:39555
    volumes:
      - ./data/ltcd:/root/.ltcd
    logging: *default-logging

  lndbtc:
    image: exchangeunion/lnd-simnet:latest
    hostname: lndbtc
    environment:
      - NETWORK=simnet
      - CHAIN=bitcoin
    volumes:
      - ./data/lndbtc:/root/.lnd
    logging: *default-logging

  lndltc:
    image: exchangeunion/lnd-simnet:latest
    hostname: lndltc
    environment:
      - NETWORK=simnet
      - CHAIN=litecoin
    volumes:
      - ./data/lndltc:/root/.lnd
      - ./data/ltcd:/root/.ltcd
    logging: *default-logging

  raiden:
    image: exchangeunion/raiden-simnet
    hostname: raiden
    environment:
      - NETWORK=simnet
    command: >
      --keystore-path /root/.raiden/keystore
      --accept-disclaimer
      --resolver-endpoint http://xud:8887/resolveraiden
      --eth-rpc-endpoint 35.231.222.142:8546
      --network-id 4321
      --password-file /root/.raiden/password.txt
      --datadir /root/.raiden
      --rpc
      --api-address 0.0.0.0:5001
      --environment-type development
      --password-file /root/.raiden/password.txt
      --no-sync-check
      --tokennetwork-registry-contract-address 0xdE8A2bdDF39C364e099D0637Dc1a7e2B8f73A4A5
      --secret-registry-contract-address 0xE51d15dEbe0F037ae787336782e3dA43ba653a8D
      --service-registry-contract-address 0x4C3Abe4F53247F03A663b55FF02fD403BaBf176d
      --one-to-n-contract-address 0x7337e831cF5BD75B0045050E6C6549cf914A923D
      --user-deposit-contract-address 0x19f8B656fBf17a83a5023eEbd675B1Ae5Bb5dF50
      --monitoring-service-contract-address 0x3B26A3d3D0c262359d1807863aE0D0FB6831D081
      --gas-price 10000000000
      --matrix-server https://raidentransport.exchangeunion.com
      --routing-mode private
    volumes:
      - ./data/raiden:/root/.raiden
    logging: *default-logging

  xud:
    image: exchangeunion/xud-simnet:latest
    hostname: xud
    environment:
      - NETWORK=simnet
    volumes:
      - ./data/xud:/root/.xud
      - ./data/lndbtc:/root/.lndbtc
      - ./data/lndltc:/root/.lndltc
    ports:
      - 28885:28885
    logging: *default-logging
