version: "3.6"
x-logging:
  &default-logging
  options:
    max-size: '20m'
    max-file: '5'
  driver: json-file

services:
  ltcd:
    image: exchangeunion/ltcd-simnet
    # Let generated "rpc.cert" has "ltcd" domain name,
    # or it will deny lnd rpc connections
    hostname: ltcd
    environment:
      - NETWORK=simnet
    command: >
      --simnet
      --txindex
      --rpcuser=xu
      --rpcpass=xu
      --rpclisten=:18556
      --nolisten
      --addpeer=35.231.222.142:39555
    ports:
      - 19556:18556
    volumes:
      - ./data/ltcd:/root/.ltcd
    logging: *default-logging

  lndbtc:
    image: exchangeunion/lnd-simnet:latest
    hostname: lndbtc
    environment:
      - NETWORK=simnet
      - CHAIN=bitcoin
    ports:
      - 10010:10009
    volumes:
      - ./data/lndbtc:/root/.lnd
    logging: *default-logging

  lndltc:
    image: exchangeunion/lnd-simnet:latest
    hostname: lndltc
    environment:
      - NETWORK=simnet
      - CHAIN=litecoin
    ports:
      - 20010:10009
    volumes:
      - ./data/lndltc:/root/.lnd
      - ./data/ltcd:/root/.ltcd
    logging: *default-logging

  raiden:
    image: exchangeunion/raiden-simnet
    hostname: raiden
    environment:
      - NETWORK=simnet
    command: >
      --keystore-path /root/.raiden/keystore
      --accept-disclaimer
      --resolver-endpoint http://xud:8887/resolveraiden
      --eth-rpc-endpoint 35.231.222.142:8546
      --network-id 4321
      --password-file /root/.raiden/password.txt
      --datadir /root/.raiden
      --rpc
      --api-address 0.0.0.0:5001
      --environment-type production
      --password-file /root/.raiden/password.txt
      --no-sync-check
      --tokennetwork-registry-contract-address 0x07679899f46422A2a9e5A3502815131Fe6d0dd0a
      --secret-registry-contract-address 0x9B16762c9f6390a19208bDE8bd8AEc81D7C6BDaB
      --endpoint-registry-contract-address 0xF6Ac1fE0421036e1f2DB6cC23CC2cFc36288d434
      --gas-price 10000000000
      --eth-rpc-endpoint 35.231.222.142:8546
      --matrix-server https://raidentransport.exchangeunion.com
      --resolver-endpoint http://localhost:8887/resolveraiden
    ports:
      - 5002:5001
    volumes:
      - ./data/raiden:/root/.raiden
    logging: *default-logging

  xud:
    image: exchangeunion/xud-simnet:latest
    hostname: xud
    environment:
      - NETWORK=simnet
    volumes:
      - ./data/xud:/root/.xud
      - ./data/lndbtc:/root/.lndbtc
      - ./data/lndltc:/root/.lndltc
    ports:
      - 9885:8885
      - 9886:8886
      - 9887:8887
    logging: *default-logging
