version: "3.6"

services:
  ltcd:
    #image: exchangeunion/ltcd:latest-simnet
    image: exchangeunion/ltcd:latest-simnet
    # Let generated "rpc.cert" has "ltcd" domain name,
    # or it will deny lnd rpc connections
    hostname: ltcd
    environment:
      - NETWORK=simnet
    command: >
      --simnet
      --txindex
      --rpcuser=xu
      --rpcpass=xu
      --rpclisten=:18556
      --nolisten
      --addpeer=35.231.222.142:39555
    ports:
      - 19556:18556
    volumes:
      - ./data/ltcd:/root/.ltcd

  lndbtc:
    image: exchangeunion/lnd:0.6.1-beta-simnet
    hostname: lndbtc
    environment:
      - NETWORK=simnet
      - CHAIN=bitcoin
    command: >
      --alias=lndbtc
      --bitcoin.active
      --bitcoin.simnet
      --bitcoin.node=neutrino
      --neutrino.connect=35.231.222.142:38555
      --debuglevel=debug
    ports:
      - 10010:10009
    volumes:
      - ./data/lndbtc:/root/.lnd
      - ./data/btcd:/root/.btcd

  lndltc:
    image: exchangeunion/lnd:0.6.1-beta-simnet
    hostname: lndltc
    environment:
      - NETWORK=simnet
      - CHAIN=litecoin
    command: >
      --alias=lndltc
      --litecoin.active
      --litecoin.simnet
      --litecoin.node=ltcd
      --ltcd.rpchost=ltcd
      --ltcd.rpcuser=xu
      --ltcd.rpcpass=xu
      --debuglevel=debug
    ports:
      - 20010:10009
    volumes:
      - ./data/lndltc:/root/.lnd
      - ./data/ltcd:/root/.ltcd

  raiden:
    image: exchangeunion/raiden:simnet
    hostname: raiden
    environment:
      - NETWORK=simnet
    command: >
      --keystore-path /root/.raiden/keystore
      --accept-disclaimer
      --resolver-endpoint http://xud:8887/resolveraiden
      --eth-rpc-endpoint 35.231.222.142:8546
      --network-id 4321
      --password-file /root/.raiden/password.txt
      --datadir /root/.raiden
      --rpc
      --api-address 0.0.0.0:5001
      --matrix-server https://raidentransport.exchangeunion.com
      --no-sync-check
      --tokennetwork-registry-contract-address 0x07679899f46422A2a9e5A3502815131Fe6d0dd0a
      --secret-registry-contract-address 0x9B16762c9f6390a19208bDE8bd8AEc81D7C6BDaB
      --endpoint-registry-contract-address 0xF6Ac1fE0421036e1f2DB6cC23CC2cFc36288d434
      --gas-price 10000000000
    ports:
      - 5002:5001
    volumes:
      - ./data/raiden:/root/.raiden

  xud:
    image: exchangeunion/xud
    hostname: xud
    environment:
      - NETWORK=simnet
    volumes:
      - ./data/xud:/root/.xud
      - ./data/lndbtc:/root/.lndbtc
      - ./data/lndltc:/root/.lndltc
    ports:
      - 9885:8885
      - 9886:8886
      - 9887:8887
