#!/bin/bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR

./build btcoind
./build litecoind
./build lnd
./build parity
./build geth
./build raiden
./build xud
./build btcd
./build ltcd
