version: "3.6"

services:
  bitcoind:
    image: exchangeunion/bitcoind:0.17.1
    hostname: bitcoind
    command: >
      -server
      -testnet
      -rpcuser=xu
      -rpcpassword=xu
      -disablewallet
      -txindex
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333
      -logips
      -rpcport=18332
      -rpcallowip=::/0
      -rpcbind=0.0.0.0
    ports:
      - 18332:18332
      - 28332:28332
      - 28333:28333
    volumes:
      - ./data/bitcoind:/root/.bitcoin

  litecoind:
    image: exchangeunion/litecoind:0.17.1
    hostname: litecoind
    # Use -reindex to solve "Failed to read block ... from disk" error
    # ref. https://bitcoin.stackexchange.com/questions/8787/failed-to-read-block
    # Disable this parameter because it will let litecoind sync from scratch after every restart
    command: >
      -server
      -testnet
      -rpcuser=xu
      -rpcpassword=xu
      -disablewallet
      -txindex
      -zmqpubrawblock=tcp://0.0.0.0:29332
      -zmqpubrawtx=tcp://0.0.0.0:29333
      -logips
      -rpcport=19332
      -rpcallowip=::/0
      -rpcbind=0.0.0.0
    ports:
      - 19332:19332
      - 29332:29332
      - 29333:29333
    volumes:
      - ./data/litecoind:/root/.litecoin

  lndbtc:
    image: exchangeunion/lnd:0.6.1-beta
    hostname: lndbtc
    environment:
      - NETWORK=testnet
      - CHAIN=bitcoin
    command: >
      --alias=lndbtc
      --bitcoin.active
      --bitcoin.testnet
      --bitcoin.node=bitcoind
      --bitcoind.rpchost=bitcoind
      --bitcoind.rpcuser=xu
      --bitcoind.rpcpass=xu
      --bitcoind.zmqpubrawblock=tcp://bitcoind:28332
      --bitcoind.zmqpubrawtx=tcp://bitcoind:28333
      --debuglevel=debug
    ports:
      - 9735:9735
      - 10009:10009
    volumes:
      - ./data/lndbtc:/root/.lnd

  lndltc:
    image: exchangeunion/lnd:0.6.1-beta
    hostname: lndltc
    environment:
      - NETWORK=testnet
      - CHAIN=litecoin
    command: >
      --alias=lndltc
      --litecoin.active
      --litecoin.testnet
      --litecoin.node=litecoind
      --litecoind.rpchost=litecoind
      --litecoind.rpcuser=xu
      --litecoind.rpcpass=xu
      --litecoind.zmqpubrawblock=tcp://litecoind:29332
      --litecoind.zmqpubrawtx=tcp://litecoind:29333
      --debuglevel=debug
    ports:
      - 10735:9735
      - 20009:10009
    volumes:
      - ./data/lndltc:/root/.lnd

  parity:
    image: exchangeunion/parity:2.4.7-stable
    environment:
      - NETWORK=testnet
    command: >
      --no-warp
      --chain ropsten
      --jsonrpc-apis eth,net,web3,parity,personal
      --jsonrpc-interface 0.0.0.0
    volumes: 
      - ./data/parity:/root/.local/share/io.parity.ethereum
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303/udp

  raiden:
    image: exchangeunion/raiden:0.100.3
    hostname: raiden
    environment:
      - NETWORK=testnet
    command: >
      --keystore-path /root/.ethereum/keys/ropsten
      --accept-disclaimer
      --eth-rpc-endpoint parity:8545
      --network-id ropsten
      --password-file /root/.ethereum/passphrase.txt
      --datadir /root/.raiden
      --rpc
      --api-address 0.0.0.0:5001
      --matrix-server https://raidentransport.exchangeunion.com
    ports:
      - 5001:5001
    volumes:
      - ./data/parity:/root/.ethereum
      - ./data/raiden:/root/.raiden
  
  xud:
    image: exchangeunion/xud
    hostname: xud
    environment:
      - NETWORK=testnet
    volumes:
      - ./data/xud:/root/.xud
      - ./data/lndbtc:/root/.lndbtc
      - ./data/lndltc:/root/.lndltc
    ports:
      - 8885:8885
      - 8886:8886
