version: "3.6"

services:
  bitcoind:
    image: exchangeunion/bitcoind
    # Let generated "rpc.cert" has "btcd" domain name,
    # or it will deny lnd rpc connections
    hostname: bitcoind
    command: >
      -server
      -testnet
      -rpcuser=xu
      -rpcpassword=xu
      -disablewallet
      -txindex
      -zmqpubrawblock=tcp://0.0.0.0:28333
      -zmqpubrawtx=tcp://0.0.0.0:28333
      -zmqpubhashblock=tcp://0.0.0.0:28333
      -zmqpubhashtx=tcp://0.0.0.0:28333
      -logips
      -rpcport=18332
      -rpcallowip=::/0
    ports:
      - 18332:18332
      - 28333:28333
    volumes:
      - ./data/bitcoind:/root/.bitcoin

  litecoind:
    image: exchangeunion/litecoind
    # Let generated "rpc.cert" has "ltcd" domain name,
    # or it will deny lnd rpc connections
    hostname: litecoind
    command: >
      -server
      -testnet
      -rpcuser=xu
      -rpcpassword=xu
      -disablewallet
      -txindex
      -zmqpubrawblock=tcp://0.0.0.0:29333
      -zmqpubrawtx=tcp://0.0.0.0:29333
      -zmqpubhashblock=tcp://0.0.0.0:29333
      -zmqpubhashtx=tcp://0.0.0.0:29333
      -logips
      -rpcport=19332
      -rpcallowip=::/0
    ports:
      - 19332:19332
      - 29333:29333
    volumes:
      - ./data/litecoind:/root/.litecoin

  lndbtc:
    image: exchangeunion/lnd
    hostname: lndbtc
    command: >
      --alias=lndbtc
      --bitcoin.active
      --bitcoin.testnet
      --bitcoin.node=bitcoind
      --bitcoin.rpcuser=xu
      --bitcoin.rpcpass=xu
      --bitcoin.zmqpubrawblock=tcp://bitcoind:28333
      --bitcoin.zmqpubrawtx=tcp://bitcoind:28333
    ports:
      - 10009:10009
    volumes:
      - ./data/lndbtc:/root/.lnd
    depends_on:
      - bitcoind

  lndltc:
    image: exchangeunion/lnd
    hostname: lndltc
    command: >
      --alias=lndltc
      --litecoin.active
      --litecoin.testnet
      --litecoin.node=litecoind
      --litecoin.rpcuser=xu
      --litecoin.rpcpass=xu
      --litecoin.zmqpubrawblock=tcp://litecoind:28333
      --litecoin.zmqpubrawtx=tcp://litecoind:28333
    ports:
      - 20009:10009
    volumes:
      - ./data/lndltc:/root/.lnd
    depends_on:
      - litecoind

  xud:
    image: exchangeunion/xud:test
    hostname: xud
    environment:
      - NETWORK=testnet
    volumes:
      - ./data/xud:/root/.xud
      - ./data/lndbtc:/root/.lndbtc
      - ./data/lndltc:/root/.lndltc
    ports:
      - 18885:8885
      - 18886:8886
    depends_on:
      - lndbtc
      - lndltc
  
  ctl:
    build: exchangeunion/ctl:dev
    environment:
      - NETWORK=testnet
    volumes:
      - ./data/lndbtc:/root/.lndbtc
      - ./data/lndltc:/root/.lndltc
  
  geth:
    image: ethereum/client-go
    command: >
      --testnet
      --syncmode fast
      --rpc
      --rpcapi eth,net,web3,txpool
    volumes: 
      - ./data/geth:/root/.ethereum
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303

  raiden:
    image: raidennetwork/raiden
    command: >
      --keystore-path /root/.ethereum/testnet/keystore
      --accept-disclaimer
    volumes:
      - ./data/geth:/root/.ethereum
