name: Launcher Build

on:
  push:
    branches:
      # Build launcher binary on any branch
      - '*'

jobs:
  build:
    name: Build artifacts
    strategy:
      matrix:
        go-version: [ 1.15.x ]
        os: [ linux, darwin, windows ]
        arch: [ amd64, arm64 ]
        exclude:
          - os: windows
            arch: arm64

    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch dependencies
        working-directory: ./launcher
        run: go mod vendor

      - name: Build
        working-directory: ./launcher
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: |
            launcher/launcher
            launcher/launcher.exe
