name: Pre-release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-*'


jobs:
  create_release:
    name: Create releases
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: true
          draft: true

  build:
    needs: create_release
    name: Build artifacts
    strategy:
      matrix:
        go-version: [ 1.15.x ]
        os: [ linux, darwin, windows ]
        arch: [ amd64 ]

    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch dependencies
        working-directory: ./launcher
        run: go mod vendor

      - name: Build
        working-directory: ./launcher
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: |
            launcher/launcher
            launcher/launcher.exe

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: launcher
          asset_name: |
            launcher
            launcher.exe
          asset_content_type: application/zip
