name: "Run tests"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          echo "No lint for now."
      - name: Test with pytest
        run: |
          pytest -s --tb native -k "test_config or test_nodes" tests
