#!/bin/bash

ctl -n $NETWORK \
    --bitcoind.address http://xu:xu@bitcoind:18332 \
    --bitcoind.datadir /root/.bitcoin \
    --litecoind.address http://xu:xu@litecoind:19332 \
    --litecoind.datadir /root/.litecoin \
    --lndbtc.address grpc://lndbtc:10009 \
    --lndbtc.datadir /root/.lndbtc \
    --lndltc.address grpc://lndltc:10009 \
    --lndltc.datadir /root/.lndltc \
    --geth.address http://geth:8545 \
    --geth.datadir /root/.ethereum \
    --raiden.address http://raiden:5001 \
    --raiden.datadir /root/.raiden \
    --xud.address grpc://xud:8886 \
    --xud.datadir /root/.xud \
    status $@
